[package]
name = "qotd"
version = "0.1.0"
authors = ["Peter Mares"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
reqwest = "0.9"